### ISSUE TITLE
[Suggest] Map Snapping

### ISSUE THREAD

**Issue by oriontribunal** [mSparks43/XPlane-11-AutoATC-plugin#10]
There are times, especially during observation of traffic that one might wish to pan the world map in one direction or the other, but whenever you do this it snaps back into place around the user's aircraft. I would suggest that the default behavior be to leave the map at the user specified position and zoom level with perhaps a little button along the bottom or side to center on user position.

The map screen is also a little bit swipe left/right happy.  You have to pan the map up or down before moving it left or right or it assumes you're attempting to... change.. panels or whatever you call them.

**Comment by mSparks43** [comment]
I left room under the map for just such a control (and perhaps others), aim to have it in after the next meeting with the designer. Current [new] design is a first draft of the chosen scheme.

**Comment by mSparks43** [comment]
fixed in android version 0.8.6.903

**Comment by oriontribunal** [comment]
Probably not worth opening another ticket for, and I really don't know anything about the internals of the mapping service, but most phones these days have storage measured in gigabytes. A hundred megs of cached maps isn't going to hurt.

It is an assumption that they're not caching-- the seem to reload a lot.

**Comment by mSparks43** [comment]
added setAppCacheEnabled(true) to map view for future release.
