### ISSUE TITLE
0.9.7.4 does not connect on Linux

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#100]
I can't get 0.9.7.4 to connect on Arch Linux. AutoATC seems to launch normally (see the attached Log.txt), but I neither get traffic inside X-Plane nor radio information in the log window nor a connection to the app. Manually connecting to my phone via device IP also does not work.

I've tried replacing the included JRE with a JRE/JDK 17.0.x releae from Adoptium or Oracle, but they either do not work or the problem persists.

Reverting to 0.9.6.1 displays traffic just fine and I am able to connect the app.

[Log.txt](https://github.com/mSparks43/XPlane-11-AutoATC-plugin/files/8036327/Log.txt)

**Comment by mSparks43** [comment]
Do you have one of the ATCLog files? everything seems to be starting normally there.

**Comment by JT8D-17** [comment]
Wow, I did not get notified about your reply. Stupid GiHub.

Anyway, 0.9.8.3 starts up and connects normally, so I'm closing this issue.
