### ISSUE TITLE
[Crash] Airport Change

### ISSUE THREAD

**Issue by oriontribunal** [mSparks43/XPlane-11-AutoATC-plugin#11]
Description:
Changing your airport from the settings menu on a fresh booting of the app before selecting anything else causes app to crash.

Repeatable:
Yes

Steps to Reproduce:
1: Fresh boot app, make sure it's not resuming anything.
2: Go to settings
3: Change your airport

Expected behavior:
Airport change. Interestingly enough, it does change the airport, it just crashes in doing so. Next time it comes up, the airport change is reflected.

**Comment by mSparks43** [comment]
trying to set the mini map location before its created.
Fixed in next android application update
