### ISSUE TITLE
Xplane crash on exit

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/XPlane-11-AutoATC-plugin#17]
In some circumstances, AutoATC Xplane plugin will cause a crash when exiting the sim

**Comment by ianac2000** [comment]
[atcid.txt](https://github.com/mSparks43/XPlane-11-AutoATC-plugin/files/3086544/atcid.txt)
[ATCLog.txt](https://github.com/mSparks43/XPlane-11-AutoATC-plugin/files/3086545/ATCLog.txt)
[Log.txt](https://github.com/mSparks43/XPlane-11-AutoATC-plugin/files/3086546/Log.txt)

**Comment by ianac2000** [comment]
have copied files to this section. Note that crash text is different now with the beta version. Used to crash thread 18 now crashes thread 11

**Comment by mSparks43** [comment]
Logging (ATCLog.txt) was turned off in the last beta (That ATCLog.txt is from an old version that had it on) , I just put a new Beta on the main install page with the (few fixes) since the last release - but most importantly logging turned on.

could you post the files again from immediately after it crashes with the latest version.

I just tried the standard tests (turn off never connecting to an android device, turn off while android is connected, turn off after android disconnected) - each of which have caused exit crashes at one point or another and couldn't recreate it, and those logs don't include any crash details.

I don't see the exit messages in the ATCLog I just created I would expect when I just "turn off never connecting to an android device" - while it didn't crash in this case, and could just be it closed before writing them to the file, it could be something is still failing to exit cleanly somewhere in this case.

Also, since this is a mac, could you run XP from a console window and include the output there, Lin/Mac have much nicer output than windows it dumps in there.

Additionally, Laminar have been bug and crash fixing XP - there's a new Beta out (11.33b1) which fixes several crash causes their side.

**Comment by mSparks43** [comment]
closing with no further action.

**Comment by mSparks43** [comment]
This should be fixed as @ XP11.35b4.

**Comment by mSparks43** [comment]
another one identified and fixed (audio player not completing in certain circumstances)

**Comment by mSparks43** [comment]
New fixes in 0.8.73

**Comment by mSparks43** [comment]
Still happening on rare occasions

**Comment by mSparks43** [comment]
Audio player interrupt had been overidden without calling its parent interrupt, new fix soon.

**Comment by mSparks43** [comment]
Should be fixed in plugin update 0.9.2 (Apr 2020) on
https://forums.x-plane.org/index.php?/files/file/45663-main-installation-files-for-autoatc-for-xplane-11/

**Comment by mSparks43** [comment]
Just happened to me again

**Comment by mSparks43** [comment]
Dare I close it again...
