### ISSUE TITLE
Incompatible plugins

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/XPlane-11-AutoATC-plugin#19]
Xplane plugins that try to load the JVM after AutoATC will  cause XP to crash.

There are two possible solutions to this, first is for the other plugin developer to adopt the 
api.XPJVMAPI﻿

described on
https://forums.x-plane.org/index.php?/forums/topic/175706-sharing-the-jvm/

Alternatively, but much less desirable it should be possible for the user to patch the offending plugin with the API and force AutoATC to load after them by changing the name of the folder.

This issue is for tracking such plugins and providing solutions

**Comment by hachirotahoshino** [comment]
Hi, i had an issue with CEF plugin from FF A320 Ultimate i comment here so that future users may know

**Comment by mSparks43** [comment]
Zibo Mod v3.34 rc1.33 works ok.

**Comment by mSparks43** [comment]
XJet app from AirFoilLabs

**Comment by mSparks43** [comment]
Flight Factor Support System
Hi.
We dont use JVM in our product.

**Comment by mSparks43** [comment]
Code updated to connect to existing JVM, live for XP plugin version 0.8.7b1
