### ISSUE TITLE
correct pronunciation of "decimal"

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/XPlane-11-AutoATC-plugin#5]
default TTS should pronounce numbers as:
https://www.youtube.com/watch?v=NufAKh0ux8E

->conflicting pronunciations?

**Comment by oriontribunal** [comment]
I can only speak for a currentish version of android [8.1 I believe], but the synthetic voices provided by Google seem, in most cases to function better with the correct spelling of the word/number or just the number. There are some obvious exceptions, such as "niner" for 9.

Saying "tree" might be a great way of teaching pilots who are not native English speakers to be understandable over the radio-- but hearing a British or Aussie accent saying "tree" for 3 is like nails on a chalkboard. The "fower" is God-awful also. It fits really well with the Indian accented lady, maybe selective phonetics?

There are also some regional dialogue issues. Now, I stress that I am not a pilot, but I do listen to a fair amount of aviation radio chatter... for fun ... I'm sure all pilots know their Q-codes, but I had to look up QNH as I've only ever heard it as "altimeter." Same story for "radar." I'm assuming that it's departure or approach, but I'm not sure.

**Comment by mSparks43** [comment]
Absolutely agreed. I have a "sounds like" option in the parser database which can pin these to (invisible) spellings to use with TTS - fower in particular has been through a few iterations but I've just gone back to "four" and decimal back to decimal.
regional variations don't seem to be documented well anywhere.
the actual "decimal" thing seems to be "point" in the US
so 
one one niner decimal one in European airspace
one one niner point one in the US
similar with QNH (European in millibars) and Altimeter (US in inches mercury)

"international aviation English" definitely not a "global standard".
At the moment I am targeting ICAO and UK CAA compatability
DOC9342 for ICAO
http://dgca.gov.in/intradgca/intra/icaodocs/Doc%209432%20-%20Manual%20Radiotelephony%20Ed%204%20(En).pdf

and
CAP413 for UK CAA
https://publicapps.caa.co.uk/docs/33/CAP413v21_6.pdf

There's some detail recently added for ground/tower/radar/centre in the current ground school start up theory.
Again, terrible material available elsewhere. Aim is to document as much as I can to ICAO standard, and have regional variations as a seperate section. Ground School still very much a WIP, so I want to get the theory good, then I'll update the AI server to match it.

**Comment by mSparks43** [comment]
I describe radar as often sub divided into departure and approach sometime even by active - this is airport dependant rather than region, since at the moment the AI is only using one active runway for all airports, approach/departure are currently all collapsed into radar.

**Comment by mSparks43** [comment]
decimal vs point regionalisation is now in testing
