### ISSUE TITLE
Adjustable AI aircraft sound levels

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#53]
AI aircraft sounds do not observe XP sound levels.
For example, muting XP (by setting "/sim/operation/sound/sound_on" to "false") does not mute AI aircraft.

Suggestion for improvement:
Tie AI aircraft sound to the corresponding XP datarefs.

**Comment by mSparks43** [comment]
Will merge #54
