### ISSUE TITLE
ATIS improvments

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#65]
1) Currently, tuning the radio to an ATIS frequency will output both AutoATC's ATIS (on the Android device) and X-Plane's ATIS.

The plugin should set
> sim/atc/atis_enabled

to 0 when...
- ...the AutoATC app is connected to the simulator
- ...the radio is tuned to an ATIS frequency

2) ATIS speech output from the app is very slow and piecemeal and needs improvement.

**Comment by mSparks43** [comment]
set atis_enabled=0 in next android update
