### ISSUE TITLE
Deleting Flight Plan App. Crash

### ISSUE THREAD

**Issue by oriontribunal** [mSparks43/XPlane-11-AutoATC-plugin#7]
This is regarding AutoATC Radio Beta [0.8.6.9].

Description:
Swiping right on "Create a new flight plan" causes app to crash.

Repeatable:
Yes.

Steps To Repeat:
1: Delete any existing flight plans that might exist, so the only entry is for creating a new plan. 
2: Swipe it right, as if to delete it.

Expected Behavior:
Either it won't allow you to attempt the deletion, ie: swipe does nothing with empty flight plan set or catches the exception and handles it. Either or.

Actual Behavior:
Kaboom.

**Comment by mSparks43** [comment]
fix applied for next android release + related bug for airframes.
