### ISSUE TITLE
App: Flight plan archive feature

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#70]
The app should have a flight plan archive that stores the last three filed flight plans for easy refiling.

**Comment by JT8D-17** [comment]
Related to https://github.com/mSparks43/XPlane-11-AutoATC-plugin/issues/82

**Comment by mSparks43** [comment]
All filed flight plans now have a "duplicate" option from apps v0.9.3.15, due to roll out in the next few days
