### ISSUE TITLE
Airspeed restriction below 10000 ft

### ISSUE THREAD

**Issue by JT8D-17** [mSparks43/XPlane-11-AutoATC-plugin#77]
The airspeed limit below 10000 ft should be 250 KIAS. So if an aircraft is not travelling faster than 250 KIAS when crossing or below 10000 ft, ATC should not issue a speed warning.

See here:
[https://www.boldmethod.com/learn-to-fly/regulations/why-is-there-a-250-knot-speed-limit-below-10000-feet/](url)

**Comment by mSparks43** [comment]
main issue is it was issuing for 250kts g/s
250kts kias is more like 320kts g/s at 10000 ft msl
