### ISSUE TITLE
Auto align sim minutes

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/XPlane-11-AutoATC-plugin#88]
need some kind of support so that sim minutes can match server minutes

**Comment by JT8D-17** [comment]
Maybe a "sync date and time" button in the app that sets XP time to server time?

**Comment by mSparks43** [comment]
the main issue is really the minutes, where aircraft are announcing times where every minute counts (e.g. they are arriving 5 minutes before you, but your clock says they are arriving at the same time) still not clear exactly how this is well synced irl.

**Comment by mSparks43** [comment]
connecting android syncs to zulu time in next update (can change afterwards - one time call)
