### ISSUE TITLE
Stand-Alone Positioning Conflict

### ISSUE THREAD

**Issue by oriontribunal** [mSparks43/XPlane-11-AutoATC-plugin#9]
As per testing suggestions, I started up AutoATC without any X-Plane interaction and put myself at Covington [KCVG]. Radio traffic was really good, lots of planes started communicating and moving but...

Description:
The personal airport selection resulted in the placement of my "aircraft location" in the middle of the airport, which was incidentally right along the taxiway the planes were wanting to use for runway 18. They all taxied just short of my indicated position [on the map] and formed a long line completely choking ground flow at KCVG.

Repeatability:
Untested, yet somehow presumed. When moved to the municipal field nearby, the traffic continued as normally-- but since it is presumably simulated on a server somewhere, traffic didn't actually reset with a program restart.

Steps to Produce:
1: Open AutoATC on Andoid and start flight
2: Set your airport to KCVG [should put you pretty much dead in the middle]
3: Observe traffic pile up behind you

Expected Behavior:
Should either ignore your position if not actually connected with a simulator, or be extra cautious to place you in a parking or otherwise non-essential traffic area.

Actual Behavior:
Rather amusing tangle of aircraft on the tarmac.

**Comment by mSparks43** [comment]
fixed in android version 0.8.6.903 (made stand alone user position invisibile to AI aircraft)
